title: Jerry · 保持探索
description: Jerry的个人空间

baseurl: "/Jerryhome"
url: "https://jerry-future666.github.io"

markdown: kramdown


collections:
  projects:
    output: true
    permalink: /projects/:name/
